### PR TITLE
Adding oAuth support to the module - fixes #23

### LINKED ISSUE #23: Supplying Servicenow API key along with Set-ServiceNowAuth
Great work and I'm looking at using this in my environment for incident automation especially.  In order to interface with Servicenow in my environment an API key in the header info is required.

Would it be possible to provide a way to input this as an optional parameter/argument as part of the Set-ServiceNowAuth?

### PR DESCRIPTION
**Pull request by brettmillerb**
This PR is to add oAuth support to the module. I closed #80 to avoid confusion as that was a WIP and I changed my mind on the implementation.

- `Set-ServiceNowAuth` is now a proxy for `Connect-ServiceNow`. This means user experience is the same but allows for oAuth, explicit passing of creds or Azure Automation
- Previous `$Global` scoped variables are no longer used instead one `$Script:ConnectionObj` hashtable is set.
- Added `Private/Get-ServiceNowOAuthToken` which allows for easy retrieval of Access Token for subsequent API calls.
- Added `Private/Get-ServiceNowFullUri` to allow for easy construction of the full API endpoint Uri.
- Updated `Get-ServiceNowIncident` to re-order logic for easier readability, removed `Mandatory = $false` from parameters as not required.
- Amended `Get-ServiceNowTable` to abstract parameterset logic so that AccessToken, Azure Automation or explicitly passing credentials is allowed. Changed `Invoke-RestMethod` call to a splat for conditional addition of parameters.
- Added `Private/New-ServiceNowConnection` to control parameterset logic to return relevant fields for `Invoke-RestMethod` based on the Auth type being used.
- Amendment of parameter values to cater for conditional Authenticiation checks. e.g. Made `UseConnectionObject` default parameter set.

This is a breaking change in that the `Set-ServiceNowAuth` no longer sets `$Global` variables but since it was setting `$Global:Credential` which is bad because it's global and it uses commonplace `$Credential` then I think this should be considered as a move in the right direction.

Not fully implemented yet but tested with Access Token for most commands and because they already pass `$Connection` directly to `Get-ServiceNowTable` they work as before.

Happy to open this up for discussion. I have tried consciously not to break current functionality whilst adding OAuth but not have to amend every function in the module.

### CODE REVIEW

**Comment by brettmillerb** [comment]
Okay so to open this up for discussion on changes I've made to allow OAuth.

- `Set-ServiceNowAuth` is now a proxy command for `Private/Connect-ServiceNow` for no other reason than I wasn't going to change the way that `Set-ServiceNowAuth` worked.
 - `Connect-ServiceNow` logic could effectively be placed in `Set-ServiceNowAuth`

- Cosmetic/layout/logic  changes to `Get-ServiceNowIncident` e.g. changing to `$PSCmdlet.ParameterSetName` instead of $null variable checks etc. 
- Changes were to `Get-ServiceNowTable` which in turn calls `Private/New-ServiceNowConnection` which is the logic to distinguish between Azure Automation and OAuth.

- DefaultParameterSet has been changed on `Get-ServiceNowIncident` to ensure the new logic is used if no parameters are set so I anticipate that this will need to be changed on each public function.

```powershell
[CmdletBinding(DefaultParameterSetName, SupportsPaging)]
```
needs to change to
```powershell
[CmdletBinding(DefaultParameterSetName = 'UseConnectionObject', SupportsPaging)]
```
- OAuth/Credentials set with Set-ServiceNowAuth work as expected for Change, Request & Incident

- Explicitly Passing `-Credental` to the functions work as expected for Change, Request & Incident

I'd like to go through and bring the rest of the functions inline so they are consistent with `DefaultParameterSet` etc but this is already quite a hefty PR with the logic change to allow for OAuth.

**Comment by Rick-2CA** [comment]
I didn't get to setup OAuth to play with and test, but did look through the code.  Some initial feedback:

* I'm going to call the parameter rework set in `Get-ServiceNowIncident` as out of scope for introducing OAuth.  We should argue our parameter configuration preferences separately.  I've got a list of changes that need standardized across everything anyway I'd like to handle on its own.  We can put removing `Mandatory = $false` on that list though. ;)
* `Set-ServiceNowAuth` is changing anyway.  There anything to gain by not incorporating the contents of `Connect-ServiceNow` with it?
* Isn't `-Credential` collecting the same information as `-UserCredential` in `Set-ServiceNowAuth`?  `-Credential` could be in the default parameter set name and a single additional parameter could be included to add the token information.  This way `Credential` is consistently your everyday username and password throughout the module.
* In `Get-ServiceNowTable` I'd rather accept specified credentials over a connection stored with `Set-ServiceNowAuth`.  The idea being that if you include it with the command it was deliberate for that one command and should override the other methods.  I occasionally use it to jump to another environment, which may be a weird use case, but a use case.
* There are 9 files that call `Invoke-RestMethod` that need to take into account the authentication method the user has asked for.  All of the commands that hit tables must collect the parameters for the set names of `SpecifyConnectionFields` or `UseConnectionObject` (assuming Azure) as they matter per command for overrides as stated above.  `Get-ServiceNowIncident` doesn't need any changes nor does any other public function that doesn't call `Invoke-RestMethod` in order to support the connection info set by `Set-ServiceNowAuth`.

**Comment by brettmillerb** [comment]
> I'm going to call the parameter rework set in `Get-ServiceNowIncident` as out of scope for introducing OAuth.  We should argue our parameter configuration preferences separately. 
>    I've got a list of changes that need standardized across everything anyway I'd like to handle on its own.  We can put removing `Mandatory = $false` on that list though. ;)

I cherry picked my updates from `Get-ServiceNowIncident` to re-instate the parameter changes. So the only thing that is changed in that function is the `DefaultParameterSetName` and the default value for the `$Connection` parameter to pick up the `$Script` scoped auth if its set.

> `Set-ServiceNowAuth` is changing anyway.  There anything to gain by not incorporating the contents of `Connect-ServiceNow` with it?

I have deleted `Connect-ServiceNow` and incorporated those changes into `Set-ServiceNowAuth` instead. This was a temporary solution whilst I figured everything out and was never intended to make it into the PR.

> Isn't `-Credential` collecting the same information as `-UserCredential` in `Set-ServiceNowAuth`?  `-Credential` could be in the default parameter set name and a single additional parameter could be included to add the token information.  This way `Credential` is consistently your everyday username and password throughout the module.

Credential is indeed collecting the same information as `$UserCredential` was and agree that this should be rationalised to only one extra parameter. I have changed this and updated the associated tests.
 
> In `Get-ServiceNowTable` I'd rather accept specified credentials over a connection stored with `Set-ServiceNowAuth`.  The idea being that if you include it with the command it was deliberate for that one command and should override the other methods.  I occasionally use it to jump to another environment, which may be a weird use case, but a use case.

This behaviour should remain the same. If you explicitly pass `-Credential` at the command line the `SpecifyConnectionFields` parameterset will be used rather than the DefaultParameterSet. The DefaultParameterSet is only used if you don't specify any credentials at all on the premise that you have already set your script scoped variables.

> There are 9 files that call `Invoke-RestMethod` that need to take into account the authentication method the user has asked for.  All of the commands that hit tables must collect the parameters for the set names of `SpecifyConnectionFields` or `UseConnectionObject` (assuming Azure) as they matter per command for overrides as stated above.  `Get-ServiceNowIncident` doesn't need any changes nor does any other public function that doesn't call `Invoke-RestMethod` in order to support the connection info set by `Set-ServiceNowAuth`.

This should now be honoured with the changes I pushed today. I need to do some further testing on the other public functions but, I think, this is the bare minimum required to add OAuth and keep backwards compatibility.

**Comment by brettmillerb** [comment]
I haven't amended the current Pester tests but tests for the functions that I added amended are there (except `Get-ServiceNowTable` which I have half finished).

Not sure if you want another RFC/Issue on the tests @Rick-2CA ?

**Comment by brettmillerb** [comment]
I haven't amended the current Pester tests but tests for the functions that I added amended are there (except `Get-ServiceNowTable` which I have half finished).

I will do some test builds with psake and update the current tests to ensure the test coverage is the same but that I haven't also broken the current testing. 👍

**Comment by brettmillerb** [comment]
Okay @Rick-2CA I finally got around to looking at this again. I've not tested with Psake as of yet as it's taken me quite a while to get back up to speed with where I left off previously.

I have validated that both OAuth and Passing explicit credentials work for all `Get-ServiceNow....` commands and will need to continue looking at the tests etc when I get the chance.

Appreciate it's been a little while. Hopefully I'll get a bit more time to spend looking at it so that we can get this merged for people to use.

Take a look at the PR and see if there's anything outstanding that I didn't resolve last time 👍

**Comment by brettmillerb** [comment]
@Rick-2CA just about finished the oAuth addition to the remainder of the functions. I know we discussed alternative avenues for this but I wanted to get this iteration done so that it was a working solution so we could discuss further.

**Left to do:**
- Attachment tests
- Figure integration testing with lack of programatically starting a dev instance.
- Expand tests to increase coverage
- Psake to compile ps1 files to single psm1
- Look at github release package zip

Happy to discuss further about any of the changes thus far.

**Comment by thetaylormcrae** [comment]
Very interested in this PR since it will address an issue we're having with basic auth challenge being disabled. Anything that needs to be tested or looked over that I could assist with at this time?

**Comment by gdbarron** [comment]
@brettmillerb, thanks for all your work on this.  It's been a while, but I've recently picked up where Rick left off.  Your work inspired the pull request #123 that was just released.  Please let me know of any suggestions, thoughts, or issues.

**Comment by brettmillerb** [comment]
> @brettmillerb, thanks for all your work on this. It's been a while, but I've recently picked up where Rick left off. Your work inspired the pull request #123 that was just released. Please let me know of any suggestions, thoughts, or issues.

That's awesome @gdbarron and glad to see someone have the time to get this finished. Shame to see the tests not to make it in but remembering how long it took me to get the tests done and the fact they'd need refactored for Pester 5, it's understandable.

I will try and give the new version a spin in the next couple of weeks. Top work 🎉

If you can set out some issues/milestones of the items that you want in future releases I will see if I can carve out some time to contribute some more and I'll try not to make it circa 2k lines of changes 😆

**Comment by gdbarron** [comment]
oauth has been added so closing this out

**Pull request closed without merging**
