### PR TITLE
Fix #131 (Add-ServiceNowAttachment not working on PowerShell 7)

### LINKED ISSUE #131: Add-ServiceNowAttachment not working on PowerShell 7.1.3
Hello,
I am seeing issues with using Add-ServiceNowAttachment on PowerShell 7.1.3. I get this error for seemingly any attachment on a TASK:

```
Add-ServiceNowAttachment -Number $Task -Table "sc_task" -File $TempFilePath

InvalidOperation: C:\Users\nscherer\Documents\PowerShell\Modules\ServiceNow\2.2.0\Public\Add-ServiceNowAttachment.ps1:118
Line |
 118 |                  $ContentType = [System.Web.MimeMapping]::GetMimeMappi …
     |                                 ~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [System.Web.MimeMapping].
```

I have tested and this works in Windows PowerShell 5.1 on the same machine. I suspect this is because System.Web.MimeMapping is not available in .NET Core.

# Environment

```
Operating System: Windows 10 1909
ServiceNow module version: 2.2.0
PowerShell version: 7.1.3
```

# Steps to reproduce

Try to attach an attachment via Add-ServiceNowAttachment.

# Expected behavior

Attachment attaches to TASK.

# Actual behavior

Cmdlet errors out.

### PR DESCRIPTION
**Pull request by natescherer**
This is a fix for Add-ServiceNowAttachment not working on PowerShell 7.

As there does not appear to be a .NET Core replacement for System.Web.MimeMapping, I created a static hash of mime types derived from https://github.com/samuelneff/MimeTypeMap/blob/master/MimeTypeMap.cs. I have tested and this works on Windows PowerShell 5.1 and PowerShell 7.1.3.

Please let me know if you have any questions!

### CODE REVIEW

**Comment by gdbarron** [comment]
Hey @natescherer, nice work on this!  I'd ask for 2 changes please, 1 small, 1 not so small 😄  Can we move this into a config file?  It feels like that's a better place for it not just aesthetically, but for reuse.  Perhaps `/ServiceNow/config/MimeTypeMap.json`?  There's an example in the .psm1 for main.json.  Also, can you throw a link to the .cs file in there?  Thanks much!

**Comment by natescherer** [comment]
Done!

**Comment by gdbarron** [comment]
Awesome, thanks, working well.  Last change and then we are good.  The .json just needs to be converted to utf8.

**Comment by natescherer** [comment]
Good catch, I did an Out-File to created the JSON from the hash and I forgot to set the encoding. It's fixed now.

**Review by gdbarron — APPROVED** [review]

**Pull request merged**
