### PR TITLE
Fix Bugs with Automatic Table Recognition on Get-ServiceNowRecord

### PR DESCRIPTION
**Pull request by natescherer**
Hey there! I discovered a couple issues when you are trying to use the automatic table recognition. Specifically I found that you still had to specify the table when using -IncludeCustomVariable. Looking in the code, it appears there are a couple places where $thisTable should be used instead of $Table. That has been corrected in my PR.

Let me know if you have any questions or corrections or anything!

### CODE REVIEW

**Comment by gdbarron** [comment]
Hey @natescherer, thanks for taking the time to look into this.  `$thisTable` is actually a config entry with multiple properties, not just the table name, so I'm not sure this is the proper fix.  Could you let me know the command you are running and error so I can try and duplicate and we can take it from there?  Thanks.

**Comment by natescherer** [comment]
Aww geez that's my bad for not properly testing this. So here's an example:

```
Get-ServiceNowRecord -Id RITM0616331 -IncludeCustomVariable

Get-ServiceNowRecord: C:\Users\nscherer\Documents\PowerShell\Modules\ServiceNow\3.0.0\Public\Get-ServiceNowRecord.ps1:280:58
Line |
 280 |  …               $customValues = Get-ServiceNowRecord @customValueParams
     |                                                       ~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Table' because it is an empty string.
```

I just *actually* tested using $thisTable.Name and it fixes it. Adding new commit now.

**Comment by gdbarron** [comment]
Looks like there's more to this.  There are some code paths where $thisTable doesn't get created and we should fix that as well.  Do you mind if we create an issue for this and then a branch we can both work on besides master and you can merge your changes into that?

**Comment by gdbarron** [comment]
https://github.com/Snow-Shell/servicenow-powershell/issues/149, branch name is fix-149

**Comment by gdbarron** [comment]
going to close this, if you could create a new PR pointing to the new branch that would be great.  thanks!

**Pull request closed without merging**
